### PR TITLE
Create Cucumber and RSpec tests, all green

### PR DESCRIPTION
**Pull request by NegativeKarma**
#35

### CODE REVIEW

**Comment by tochman** [comment]
The PR title should be the same as the feature title it solves. The problem with this one is that there is no User Story attached to the Feature

**Comment by tochman** [comment]
Please use branch names that reflect what the feature is about. `first_databases` is not a descriptive name in this case.

**Comment by NegativeKarma** [comment]
I will attach User story and I will name branches in a proper way

**Comment by marizaswart** [comment]
Closing this pull request, code not merged with master.

**Pull request closed without merging**
